const { contextBridge, ipcRenderer } = require('electron');

function coreCall(scope, method, ...args) {
  const result = ipcRenderer.sendSync('core:call', { scope, method, args });
  if (!result?.ok) throw new Error(result?.error || `核心调用失败：${scope}.${method}`);
  return result.value;
}

function coreFn(scope, method) {
  return (...args) => coreCall(scope, method, ...args);
}

function dbFn(method) {
  return coreFn('database', method);
}

const databaseStatus = () => coreCall('meta', 'databaseStatus');
const exporterConstants = coreCall('meta', 'exporterConstants');

const databaseApi = {
  dbImportCSV: dbFn('importFromCSV'),
  dbFindCode: dbFn('findCode'),
  dbSearchActressTag: dbFn('searchActressTag'),
  dbGetOrCreateActressTag: dbFn('getOrCreateActressTag'),
  dbUpsertCode: dbFn('upsertCode'),
  dbPersistProcessedCode: dbFn('persistProcessedCode'),
  dbLinkActressCode: dbFn('linkActressCode'),
  dbLinkGenreCode: dbFn('linkGenreCode'),
  dbGetStats: dbFn('getStats'),
  dbGetActressLibrary: dbFn('getActressLibrary'),
  dbGetCodeLibrary: dbFn('getCodeLibrary'),
  dbGetCodeLibraryPage: dbFn('getCodeLibraryPage'),
  dbGetCodeLibraryIds: dbFn('getCodeLibraryIds'),
  dbGetCodeLibraryByIds: dbFn('getCodeLibraryByIds'),
  dbGetBookmarkLibrary: dbFn('getBookmarkLibrary'),
  dbGetBookmarkStats: dbFn('getBookmarkStats'),
  dbGetBookmarkCollections: dbFn('getBookmarkCollections'),
  dbGetBookmarkCollectionInfo: dbFn('getBookmarkCollectionInfo'),
  dbCreateBookmarkCollection: dbFn('createBookmarkCollection'),
  dbRenameBookmarkCollection: dbFn('renameBookmarkCollection'),
  dbDeleteBookmarkCollection: dbFn('deleteBookmarkCollection'),
  dbGetBookmarkScopeInfo: dbFn('getBookmarkScopeInfo'),
  dbDeleteBookmarksByScope: dbFn('deleteBookmarksByScope'),
  dbImportRaindropRecords: dbFn('importRaindropRecords'),
  dbBuildRaindropExport: dbFn('buildRaindropExport'),
  dbExportRaindropRecords: dbFn('exportRaindropRecords'),
  dbCreateBookmarkRecord: dbFn('createBookmarkRecord'),
  dbUpdateBookmarkRecord: dbFn('updateBookmarkRecord'),
  dbDeleteBookmarkRecord: dbFn('deleteBookmarkRecord'),
  dbAnalyzeCodeImport: dbFn('analyzeCodeImport'),
  dbImportHistoricalCodes: dbFn('importHistoricalCodes'),
  dbImportHistoricalRecords: dbFn('importHistoricalRecords'),
  dbGetRaindropImportRows: dbFn('getRaindropImportRows'),
  dbGetDuplicateCodeGroups: dbFn('getDuplicateCodeGroups'),
  dbGetHealthReport: dbFn('getHealthReport'),
  dbCleanupOrphanTags: dbFn('cleanupOrphanTags'),
  dbCleanupBrokenRelations: dbFn('cleanupBrokenRelations'),
  dbCreateBackup: dbFn('createBackup'),
  dbListBackups: dbFn('listBackups'),
  dbDeleteBackup: dbFn('deleteBackup'),
  dbRestoreBackup: dbFn('restoreBackup'),
  dbGetBackupDirectory: dbFn('getBackupDirectory'),
  dbGetDatabaseInventory: dbFn('getDatabaseInventory'),
  dbResetAllBusinessData: dbFn('resetAllBusinessData'),
  dbRenameActressTag: dbFn('renameActressTag'),
  dbMergeActressTags: dbFn('mergeActressTags'),
  dbGetGenreLibrary: dbFn('getGenreLibrary'),
  dbCreateGenreTag: dbFn('createGenreTag'),
  dbRenameGenreTag: dbFn('renameGenreTag'),
  dbDeleteGenreTag: dbFn('deleteGenreTag'),
  dbCreateActressTag: dbFn('createActressTag'),
  dbDeleteActressTag: dbFn('deleteActressTag'),
  dbCreateCodeRecord: dbFn('createCodeRecord'),
  dbUpdateCodeRecord: dbFn('updateCodeRecord'),
  dbDeleteCodeRecord: dbFn('deleteCodeRecord'),
  dbSetCodeActressTags: dbFn('setCodeActressTags'),
  dbSetCodeGenreTags: dbFn('setCodeGenreTags'),
  dbGetEditableTables: dbFn('getEditableTables'),
  dbGetRawTableRows: dbFn('getRawTableRows'),
  dbUpdateRawCell: dbFn('updateRawCell'),
  dbBulkUpdateRawCells: dbFn('bulkUpdateRawCells'),
  dbInsertRawRow: dbFn('insertRawRow'),
  dbDeleteRawRow: dbFn('deleteRawRow'),
  dbBulkDeleteRawRows: dbFn('bulkDeleteRawRows'),
  dbExportRawTableRows: dbFn('exportRawTableRows'),
  dbExportCSV: dbFn('exportToCSV'),
  dbCreateRun: dbFn('createProcessingRun'),
  dbMarkRunItemRunning: dbFn('markProcessingRunItemRunning'),
  dbUpdateRunItem: dbFn('updateProcessingRunItem'),
  dbCompleteMissavRunItem: dbFn('completeMissavProcessingRunItem'),
  dbUpdateRunTask: dbFn('updateProcessingItemTask'),
  dbCompleteRunTaskWithCache: dbFn('completeProcessingItemTaskWithCache'),
  dbGetRemoteSyncRecord: dbFn('getRemoteSyncRecord'),
  dbCompleteRemoteSyncTask: dbFn('completeRemoteSyncTask'),
  dbGetTelegramSource: dbFn('getTelegramSource'),
  dbUpsertTelegramSource: dbFn('upsertTelegramSource'),
  dbGetTelegramGroupSources: dbFn('getTelegramGroupSources'),
  dbSetTelegramGroupSources: dbFn('setTelegramGroupSources'),
  dbRecordTelegramImport: dbFn('recordTelegramImport'),
  dbGetTelegramImportHistory: dbFn('getTelegramImportHistory'),
  dbGetSiteLookupCache: dbFn('getSiteLookupCache'),
  dbSetRunStatus: dbFn('setProcessingRunStatus'),
  dbFinishRun: dbFn('finishProcessingRun'),
  dbGetRecentRuns: dbFn('getRecentRuns'),
  dbGetRun: dbFn('getProcessingRun'),
  dbGetRunItem: dbFn('getProcessingRunItem'),
  dbGetRunItems: dbFn('getProcessingRunItems'),
  dbGetResumableRun: dbFn('getResumableProcessingRun'),
  dbRenameRun: dbFn('renameProcessingRun'),
  dbDeleteRun: dbFn('deleteProcessingRun'),
  dbSetRunSpeedSettings: dbFn('setProcessingRunSpeedSettings'),
  dbSetRunOutputDir: dbFn('setProcessingRunOutputDir'),
};

contextBridge.exposeInMainWorld('electronAPI', {
  appVersion: ipcRenderer.sendSync('app:get-version-sync'),
  listTools: coreFn('tools', 'listTools'),
  getTool: coreFn('tools', 'getTool'),

  openFile: options => ipcRenderer.invoke('dialog:openFile', options),
  openDirectory: options => ipcRenderer.invoke('dialog:openDirectory', options),
  getDatabaseLocation: () => ipcRenderer.invoke('database-location:status'),
  changeDatabaseLocation: () => ipcRenderer.invoke('database-location:change'),
  readFile: (filePath, encoding) => ipcRenderer.invoke('fs:readFile', filePath, encoding),
  writeFile: (filePath, content, encoding) => ipcRenderer.invoke('fs:writeFile', filePath, content, encoding),
  createDirectory: dirPath => ipcRenderer.invoke('fs:createDirectory', dirPath),
  fileExists: filePath => ipcRenderer.invoke('fs:exists', filePath),
  readDir: dirPath => ipcRenderer.invoke('fs:readDir', dirPath),
  parseTelegramExport: paths => ipcRenderer.invoke('telegram:parse-export', paths),

  extractTwitterProfiles: coreFn('toolbox', 'extractTwitterProfiles'),
  extractBadNewsLinks: coreFn('toolbox', 'extractBadNewsLinks'),
  filterTelegramMessagesByTime: coreFn('toolbox', 'filterMessagesByTime'),
  telegramMessageTimeExtent: coreFn('toolbox', 'messageTimeExtent'),

  getTelegramBotStatus: () => ipcRenderer.invoke('telegram-bot:status'),
  connectTelegramBot: options => ipcRenderer.invoke('telegram-bot:connect', options),
  connectTelegramBotStored: () => ipcRenderer.invoke('telegram-bot:connect-stored'),
  clearTelegramBot: () => ipcRenderer.invoke('telegram-bot:clear'),
  discoverTelegramBotGroups: options => ipcRenderer.invoke('telegram-bot:discover', options),
  fetchTelegramBotUpdates: options => ipcRenderer.invoke('telegram-bot:updates', options),
  getTelegramStatus: () => ipcRenderer.invoke('telegram:status'),
  connectTelegramStored: () => ipcRenderer.invoke('telegram:connect-stored'),
  startTelegramAuthorization: options => ipcRenderer.invoke('telegram:auth-start', options),
  startTelegramQrAuthorization: options => ipcRenderer.invoke('telegram:auth-start-qr', options),
  submitTelegramAuthorization: options => ipcRenderer.invoke('telegram:auth-submit', options),
  cancelTelegramAuthorization: () => ipcRenderer.invoke('telegram:auth-cancel'),
  logoutTelegram: () => ipcRenderer.invoke('telegram:logout'),
  listTelegramGroups: () => ipcRenderer.invoke('telegram:list-groups'),
  syncTelegramGroup: options => ipcRenderer.invoke('telegram:sync-group', options),
  stopTelegramSync: () => ipcRenderer.invoke('telegram:sync-stop'),
  onTelegramState: callback => {
    const listener = (_event, state) => callback(state);
    ipcRenderer.on('telegram:state', listener);
    return () => ipcRenderer.removeListener('telegram:state', listener);
  },
  onTelegramProgress: callback => {
    const listener = (_event, progress) => callback(progress);
    ipcRenderer.on('telegram:progress', listener);
    return () => ipcRenderer.removeListener('telegram:progress', listener);
  },

  fetchPage: (url, options) => ipcRenderer.invoke('net:fetch-page', url, options),
  fetch123AvPage: (url, options) => ipcRenderer.invoke('net:fetch123av-page', url, options),
  open123AvAccountWindow: options => ipcRenderer.invoke('123av-account:open', options),
  check123AvAccount: options => ipcRenderer.invoke('123av-account:check', options),
  favorite123AvItem: options => ipcRenderer.invoke('123av-account:favorite', options),
  getChromeFavoriteBridgeStatus: () => ipcRenderer.invoke('chrome-favorite:status'),
  prepareChromeFavoriteExtension: () => ipcRenderer.invoke('chrome-favorite:prepare'),
  getRaindropAuthStatus: () => ipcRenderer.invoke('raindrop:auth-status'),
  setRaindropToken: token => ipcRenderer.invoke('raindrop:set-token', token),
  clearRaindropToken: () => ipcRenderer.invoke('raindrop:clear-token'),
  testRaindropAccount: () => ipcRenderer.invoke('raindrop:test'),
  getRaindropCollections: () => ipcRenderer.invoke('raindrop:collections'),
  ensureRaindropCollections: names => ipcRenderer.invoke('raindrop:ensure-collections', names),
  checkRaindropUrls: urls => ipcRenderer.invoke('raindrop:check-urls', urls),
  upsertRaindropItem: options => ipcRenderer.invoke('raindrop:upsert', options),

  csvParse: coreFn('csv', 'parseCSV'),
  csvStringify: coreFn('csv', 'stringifyCSV'),
  csvAnalyze: coreFn('csv', 'analyzeCSV'),
  parseRaindropCSV: coreFn('raindrop', 'parseRaindropCSV'),
  parseRaindropHTML: coreFn('raindrop', 'parseRaindropHTML'),
  generateOfficialRaindropCSV: coreFn('raindrop', 'generateRaindropCSV'),
  generateOfficialRaindropHTML: coreFn('raindrop', 'generateRaindropHTML'),
  buildRaindropSyncPayload: coreFn('raindropApi', 'buildSyncPayload'),
  raindropPayloadHash: coreFn('raindropApi', 'payloadHash'),
  selectMissavRaindropCollection: coreFn('raindropApi', 'selectMissavCollectionName'),

  openExternal: url => ipcRenderer.invoke('shell:openExternal', url),
  showDirectory: dirPath => ipcRenderer.invoke('shell:openDirectory', dirPath),
  getPath: name => ipcRenderer.invoke('app:getPath', name),
  logAppend: entry => ipcRenderer.invoke('logs:append', entry),
  logReadRecent: maxBytes => ipcRenderer.invoke('logs:readRecent', maxBytes),
  logGetInfo: () => ipcRenderer.invoke('logs:getInfo'),

  dbIsReady: () => databaseStatus().ready,
  dbGetError: () => databaseStatus().error,
  dbGetPath: () => databaseStatus().path,
  dbCheckpoint: () => {
    coreCall('database', 'save', 'FULL');
    return true;
  },
  ...databaseApi,

  normalizeCode: coreFn('parser', 'normalizeCode'),
  extractFC2Number: coreFn('parser', 'extractFC2Number'),
  codeComparableKey: coreFn('parser', 'codeComparableKey'),
  candidateUrls: coreFn('parser', 'candidateUrls'),
  parseCodeList: coreFn('input', 'parseInputCodeList'),
  checkPageStatus: coreFn('fetcher', 'checkPageStatus'),
  classifyCandidateResponse: coreFn('fetcher', 'classifyCandidateResponse'),
  resolveCandidateAttempts: coreFn('fetcher', 'resolveCandidateAttempts'),
  shouldStopCandidateSearch: coreFn('fetcher', 'shouldStopCandidateSearch'),
  extractActressTags: coreFn('fetcher', 'extractActressTags'),
  extractGenreTags: coreFn('fetcher', 'extractGenreTags'),
  build123AvSearchUrl: coreFn('av123', 'buildSearchUrl'),
  build123AvDetailUrl: coreFn('av123', 'buildDetailUrl'),
  build123AvDetailCandidateUrls: coreFn('av123', 'buildDetailCandidateUrls'),
  classify123AvResponse: coreFn('av123', 'classifyResponse'),
  buildOutputRow: coreFn('exporter', 'buildOutputRow'),
  generateRaindropHTML: coreFn('exporter', 'generateRaindropHTML'),
  generateRaindropCSV: coreFn('exporter', 'generateRaindropCSV'),
  generateReportCSV: coreFn('exporter', 'generateReportCSV'),
  buildTagExportGroups: coreFn('exporter', 'buildTagExportGroups'),
  generateTagExportIndexCSV: coreFn('exporter', 'generateTagExportIndexCSV'),
  generateTagCollectionCSV: dbFn('exportToCSV'),
  generateBackupJSON: coreFn('exporter', 'generateBackupJSON'),
  isManualVerifyRow: coreFn('exporter', 'isManualVerifyRow'),
  timePrefixToMinute: coreFn('exporter', 'timePrefixToMinute'),
  MANUAL_VERIFY_FOLDER: exporterConstants.MANUAL_VERIFY_FOLDER,
  MAIN_FOLDER: exporterConstants.MAIN_FOLDER,
  NEED_CHECK_TAG: exporterConstants.NEED_CHECK_TAG,
  UNKNOWN_ACTRESS_TAG: exporterConstants.UNKNOWN_ACTRESS_TAG,
  sleep: ms => new Promise(resolve => setTimeout(resolve, Math.max(0, Number(ms) || 0))),
});
