"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { RecordRow, ToolId } from "../../lib/types";

type Listing={rows:RecordRow[];total:number;page:number;pageSize:number};
type Selection={mode:"ids";ids:Set<string>}|{mode:"all";excluded:Set<string>};
const fieldLabels:Record<string,string>={primaryValue:"主值",secondaryValue:"辅助值",status:"状态",tags:"标签",actressTags:"女优标签",genreTags:"类型标签",sourceUrl:"来源链接",missavUrl:"MissAV 链接",av123Url:"123AV 链接"};
async function api(url:string,options?:RequestInit){const response=await fetch(url,options);const payload=await response.json().catch(()=>({error:"请求失败"}));if(!response.ok)throw new Error(payload.error||"请求失败");return payload;}
function selectionBody(selection:Selection,filters:Record<string,string>){return selection.mode==="all"?{mode:"all",excludeIds:[...selection.excluded],filters}:{mode:"ids",ids:[...selection.ids]};}
function cell(row:RecordRow,field:string):unknown{return row[field as keyof RecordRow];}

export default function DataCenter({refreshKey}:{refreshKey:number}){
  const [data,setData]=useState<Listing>({rows:[],total:0,page:1,pageSize:50}); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState("");
  const [search,setSearch]=useState(""); const [tool,setTool]=useState(""); const [status,setStatus]=useState(""); const [sort,setSort]=useState("updatedAt"); const [direction,setDirection]=useState<"asc"|"desc">("desc"); const [page,setPage]=useState(1); const [pageSize,setPageSize]=useState(50);
  const [selection,setSelection]=useState<Selection>({mode:"ids",ids:new Set()}); const [bulkField,setBulkField]=useState("status"); const [bulkValue,setBulkValue]=useState(""); const lastIndex=useRef<number|null>(null);
  const filters=useMemo(()=>({search,tool,status,sort,direction}),[search,tool,status,sort,direction]);
  const load=useCallback(async()=>{setLoading(true);try{const params=new URLSearchParams({page:String(page),pageSize:String(pageSize),...filters});setData(await api(`/api/records?${params}`));}catch(error){setNotice(error instanceof Error?error.message:"读取失败");}finally{setLoading(false);}},[page,pageSize,filters]);
  useEffect(()=>{const timeout=setTimeout(load,search?260:0);return()=>clearTimeout(timeout);},[load,refreshKey,search]);
  const selectedCount=selection.mode==="all"?Math.max(0,data.total-selection.excluded.size):selection.ids.size;
  const isSelected=(id:string)=>selection.mode==="all"?!selection.excluded.has(id):selection.ids.has(id);
  function toggleRow(index:number,event:React.MouseEvent){const id=data.rows[index].id; if(selection.mode==="all"){const excluded=new Set(selection.excluded);if(excluded.has(id))excluded.delete(id);else excluded.add(id);setSelection({mode:"all",excluded});return;} const ids=new Set(selection.ids);if(event.shiftKey&&lastIndex.current!==null){const[from,to]=[lastIndex.current,index].sort((a,b)=>a-b);if(!event.ctrlKey&&!event.metaKey)ids.clear();for(let i=from;i<=to;i+=1)ids.add(data.rows[i].id);}else if(event.ctrlKey||event.metaKey){if(ids.has(id))ids.delete(id);else ids.add(id);}else{ids.clear();ids.add(id);}lastIndex.current=index;setSelection({mode:"ids",ids});}
  function togglePage(){const every=data.rows.length>0&&data.rows.every(row=>isSelected(row.id));if(selection.mode==="all"){const excluded=new Set(selection.excluded);data.rows.forEach(row=>every?excluded.add(row.id):excluded.delete(row.id));setSelection({mode:"all",excluded});}else{const ids=new Set(selection.ids);data.rows.forEach(row=>every?ids.delete(row.id):ids.add(row.id));setSelection({mode:"ids",ids});}}
  function sortBy(field:string){if(sort===field)setDirection(value=>value==="asc"?"desc":"asc");else{setSort(field);setDirection("asc");}setPage(1);}
  async function edit(row:RecordRow,field:string){const original=cell(row,field);const text=Array.isArray(original)?original.join("\n"):String(original??"");const next=window.prompt(`编辑${fieldLabels[field]||field}${Array.isArray(original)?"（每行一个）":""}`,text);if(next===null)return;const value=Array.isArray(original)?next.split(/\r?\n|[,，]/).map(item=>item.trim()).filter(Boolean):next;try{await api("/api/records",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id,field,value})});setNotice("单元格已保存");load();}catch(error){setNotice(error instanceof Error?error.message:"保存失败");}}
  async function bulk(action:"update"|"delete"){if(!selectedCount)return;if(action==="delete"&&!window.confirm(`确认删除 ${selectedCount.toLocaleString()} 条记录？此操作不可撤销。`))return;try{const payload={...selectionBody(selection,filters),...(action==="update"?{action:"bulk-update",field:bulkField,value:["tags","actressTags","genreTags"].includes(bulkField)?bulkValue.split(/\r?\n|[,，]/).map(item=>item.trim()).filter(Boolean):bulkValue}:{})};await api("/api/records",{method:action==="delete"?"DELETE":"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});setNotice(`${action==="delete"?"删除":"修改"}完成`);setSelection({mode:"ids",ids:new Set()});load();}catch(error){setNotice(error instanceof Error?error.message:"操作失败");}}
  async function add(){const toolInput=window.prompt("工具：twitter / badnews / haijiao / missav","missav") as ToolId|null;if(!toolInput)return;const value=window.prompt("主值（如番号或链接）","");if(!value)return;try{await api("/api/records",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({tool:toolInput,recordKey:value.toLowerCase(),primaryValue:value,status:"manual"})});setNotice("记录已新增");load();}catch(error){setNotice(error instanceof Error?error.message:"新增失败");}}
  function copy(){const rows=data.rows.filter(row=>isSelected(row.id));const text=rows.map(row=>[row.tool,row.primaryValue,row.secondaryValue,row.status,row.tags.join("|")].join("\t")).join("\r\n");navigator.clipboard.writeText(text);setNotice(selection.mode==="all"?"已复制当前页选中项；全部记录请使用导出":"已复制选中项");}
  function exportData(format:"csv"|"json"){const params=new URLSearchParams({format,search,tool,status});window.location.href=`/api/export?${params}`;}
  function exportRaindrop(format:"csv"|"html"){const params=new URLSearchParams({format,search,status});window.location.href=`/api/raindrop?${params}`;}
  const pages=Math.max(1,Math.ceil(data.total/pageSize));
  return <div className="stack-md"><section className="data-toolbar card"><div className="searchbox"><span>⌕</span><input value={search} onChange={event=>{setSearch(event.target.value);setPage(1);setSelection({mode:"ids",ids:new Set()});}} placeholder="搜索番号、链接、标签或状态…"/></div><select value={tool} onChange={event=>{setTool(event.target.value);setPage(1);setSelection({mode:"ids",ids:new Set()});}}><option value="">全部工具</option><option value="twitter">推特博主</option><option value="badnews">Bad.news</option><option value="haijiao">海角</option><option value="missav">MissAV</option></select><input className="status-filter" value={status} onChange={event=>{setStatus(event.target.value);setPage(1);setSelection({mode:"ids",ids:new Set()});}} placeholder="状态筛选"/><button onClick={add}>＋ 新增记录</button><button onClick={()=>exportData("csv")}>导出 CSV</button><button onClick={()=>exportData("json")}>JSON</button><button onClick={()=>exportRaindrop("csv")}>Raindrop CSV</button><button onClick={()=>exportRaindrop("html")}>书签 HTML</button></section>
    {notice&&<div className="notice">{notice}</div>}
    {selectedCount>0&&<section className="bulkbar"><strong>已选 {selectedCount.toLocaleString()} 条</strong>{selection.mode==="ids"&&selectedCount<data.total&&<button onClick={()=>setSelection({mode:"all",excluded:new Set()})}>选择筛选结果全部 {data.total.toLocaleString()} 条</button>}<select value={bulkField} onChange={event=>setBulkField(event.target.value)}>{Object.entries(fieldLabels).map(([field,label])=><option value={field} key={field}>{label}</option>)}</select><input value={bulkValue} onChange={event=>setBulkValue(event.target.value)} placeholder="批量新值"/><button onClick={()=>bulk("update")}>批量修改</button><button onClick={copy}>复制当前页</button><button className="danger" onClick={()=>bulk("delete")}>删除</button><button onClick={()=>setSelection({mode:"ids",ids:new Set()})}>取消</button></section>}
    <section className="table-card"><div className="table-meta"><span>{loading?"读取中…":`共 ${data.total.toLocaleString()} 条 · 服务端分页`}</span><span>双击单元格编辑 · Ctrl/⌘ 多选 · Shift 连选</span></div><div className="table-scroll"><table className="sheet"><thead><tr><th className="check"><input type="checkbox" checked={data.rows.length>0&&data.rows.every(row=>isSelected(row.id))} onChange={togglePage}/></th><th onClick={()=>sortBy("tool")}>工具 {sort==="tool"&&(direction==="asc"?"↑":"↓")}</th><th onClick={()=>sortBy("primaryValue")}>主值 {sort==="primaryValue"&&(direction==="asc"?"↑":"↓")}</th><th>辅助值</th><th onClick={()=>sortBy("status")}>状态 {sort==="status"&&(direction==="asc"?"↑":"↓")}</th><th>标签</th><th>女优标签</th><th>来源</th><th onClick={()=>sortBy("updatedAt")}>更新时间 {sort==="updatedAt"&&(direction==="asc"?"↑":"↓")}</th></tr></thead><tbody>{data.rows.map((row,index)=><tr key={row.id} className={isSelected(row.id)?"selected":""} onClick={event=>toggleRow(index,event)}><td className="check"><input type="checkbox" readOnly checked={isSelected(row.id)}/></td><td><span className={`tool-chip ${row.tool}`}>{row.tool}</span></td><td className="strong-cell" onDoubleClick={event=>{event.stopPropagation();edit(row,"primaryValue");}}>{row.primaryValue}</td><td onDoubleClick={event=>{event.stopPropagation();edit(row,"secondaryValue");}}>{row.secondaryValue||"—"}</td><td onDoubleClick={event=>{event.stopPropagation();edit(row,"status");}}><span className="status-chip">{row.status}</span></td><td onDoubleClick={event=>{event.stopPropagation();edit(row,"tags");}}>{row.tags.join(" · ")||"—"}</td><td onDoubleClick={event=>{event.stopPropagation();edit(row,"actressTags");}}>{row.actressTags.join(" · ")||"—"}</td><td onDoubleClick={event=>{event.stopPropagation();edit(row,"sourceUrl");}}>{row.sourceUrl?<a href={row.sourceUrl} onClick={event=>event.stopPropagation()} target="_blank" rel="noreferrer">打开 ↗</a>:"—"}</td><td>{new Date(row.updatedAt).toLocaleString("zh-CN")}</td></tr>)}{!loading&&!data.rows.length&&<tr><td colSpan={9}><div className="empty compact"><strong>没有符合条件的记录</strong><p>先运行内容处理，或导入一份脱敏数据。</p></div></td></tr>}</tbody></table></div><footer className="pagination"><label>每页 <select value={pageSize} onChange={event=>{setPageSize(Number(event.target.value));setPage(1);}}><option>20</option><option>50</option><option>100</option><option>200</option></select></label><span>第 {page} / {pages} 页</span><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}>上一页</button><button disabled={page>=pages} onClick={()=>setPage(value=>value+1)}>下一页</button></footer></section>
  </div>;
}
