"use client";

import { useCallback, useEffect, useState } from "react";
type Run={id:string;tool:string;name:string;result_count:number;source_summary:string;created_at:string};
type Detail={run:Run;results:Array<Record<string,unknown>>};
async function api(url:string,options?:RequestInit){const response=await fetch(url,options);const payload=await response.json().catch(()=>({error:"请求失败"}));if(!response.ok)throw new Error(payload.error||"请求失败");return payload;}
export default function HistoryPanel({refreshKey}:{refreshKey:number}){const [rows,setRows]=useState<Run[]>([]);const [search,setSearch]=useState("");const [tool,setTool]=useState("");const [detail,setDetail]=useState<Detail|null>(null);const [notice,setNotice]=useState("");
  const load=useCallback(()=>{const params=new URLSearchParams({search,tool,pageSize:"100"});api(`/api/runs?${params}`).then(payload=>setRows(payload.rows)).catch(error=>setNotice(error.message));},[search,tool]);useEffect(()=>{const timer=setTimeout(load,200);return()=>clearTimeout(timer);},[load,refreshKey]);
  async function open(id:string){try{setDetail(await api(`/api/runs?id=${id}`));}catch(error){setNotice(error instanceof Error?error.message:"读取失败");}}
  async function rename(run:Run){const name=window.prompt("新的历史名称",run.name);if(!name)return;await api("/api/runs",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:run.id,name})});load();}
  async function remove(run:Run){if(!window.confirm(`删除历史“${run.name}”？对应永久数据不会自动删除。`))return;await api(`/api/runs?id=${run.id}`,{method:"DELETE"});if(detail?.run.id===run.id)setDetail(null);load();}
  function exportDetail(){if(!detail)return;const url=URL.createObjectURL(new Blob([JSON.stringify(detail,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`history-${detail.run.id}.json`;a.click();URL.revokeObjectURL(url);}
  return <div className="history-layout"><section className="card history-list"><div className="section-heading"><div><span className="eyebrow">永久历史</span><h3>处理批次</h3></div><span className="count-chip">{rows.length}</span></div><div className="filter-row"><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="搜索历史名称"/><select value={tool} onChange={event=>setTool(event.target.value)}><option value="">全部工具</option><option value="twitter">推特</option><option value="badnews">Bad.news</option><option value="haijiao">海角</option><option value="missav">MissAV</option></select></div>{notice&&<div className="notice">{notice}</div>}<div className="run-list">{rows.map(run=><button key={run.id} className={detail?.run.id===run.id?"active":""} onClick={()=>open(run.id)}><span className={`tool-chip ${run.tool}`}>{run.tool}</span><div><strong>{run.name}</strong><small>{run.result_count.toLocaleString()} 条 · {new Date(run.created_at).toLocaleString("zh-CN")}</small></div><span>›</span></button>)}{!rows.length&&<div className="empty compact"><strong>暂无历史</strong><p>内容处理结果保存后会出现在这里。</p></div>}</div></section><section className="card history-detail">{detail?<><div className="section-heading"><div><span className="eyebrow">批次详情</span><h3>{detail.run.name}</h3></div><div className="button-row"><button onClick={()=>rename(detail.run)}>重命名</button><button onClick={exportDetail}>导出 JSON</button><button className="danger" onClick={()=>remove(detail.run)}>删除</button></div></div><dl className="detail-meta"><div><dt>工具</dt><dd>{detail.run.tool}</dd></div><div><dt>结果</dt><dd>{detail.results.length.toLocaleString()} 条</dd></div><div><dt>来源</dt><dd>{detail.run.source_summary||"—"}</dd></div></dl><div className="detail-results">{detail.results.slice(0,500).map((row,index)=><div key={String(row.id)}><span>{index+1}</span><strong>{String(row.primary_value)}</strong><small>{String(row.secondary_value||row.source||"")}</small></div>)}</div>{detail.results.length>500&&<p className="hint">页面只预览前 500 条；导出文件包含完整批次。</p>}</>:<div className="empty"><span>◷</span><strong>选择一条处理历史</strong><p>查看批次来源、结果，或进行重命名与导出。</p></div>}</section></div>;
}
