"use client";

import { useEffect, useState } from "react";
import { parseList } from "../../lib/rules";

type Settings={referenceTags?:string[];referenceBlacklist?:string[];exportBlacklist?:string[]};
async function api(url:string,options?:RequestInit){const response=await fetch(url,options);const payload=await response.json();if(!response.ok)throw new Error(payload.error||"请求失败");return payload;}
export default function LibraryPanel(){
  const [values,setValues]=useState({referenceTags:"",referenceBlacklist:"",exportBlacklist:""}); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(true);
  useEffect(()=>{api("/api/settings").then(async(settings:Settings)=>{let tags=settings.referenceTags||[];if(!tags.length){const response=await fetch("/default-reference-tags.txt");if(response.ok)tags=parseList(await response.text());}setValues({referenceTags:tags.join("\n"),referenceBlacklist:(settings.referenceBlacklist||[]).join("\n"),exportBlacklist:(settings.exportBlacklist||[]).join("\n")});}).catch(error=>setNotice(error.message)).finally(()=>setBusy(false));},[]);
  async function save(){setBusy(true);try{const payload=Object.fromEntries(Object.entries(values).map(([key,value])=>[key,parseList(value)]));await api("/api/settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});setNotice("规则资料库已保存到 Sites 持久化数据库");}catch(error){setNotice(error instanceof Error?error.message:"保存失败");}finally{setBusy(false);}}
  return <div className="stack-lg"><section className="callout"><strong>三套列表，职责分离</strong><p>参考女优 Tag 库只用于识别与标注；参考库黑名单影响识别匹配；导出黑名单用于最终结果剔除。每行一个值，正式数据不会写入 Local Storage。</p></section><section className="library-grid"><Editor title="参考女优 Tag 库" badge="识别" value={values.referenceTags} onChange={value=>setValues(current=>({...current,referenceTags:value}))} note="用于从文本与番号记录中识别参考女优 Tag。"/><Editor title="参考库黑名单" badge="第一层" value={values.referenceBlacklist} onChange={value=>setValues(current=>({...current,referenceBlacklist:value}))} note="这些 Tag 不参与参考库匹配，不等于删除永久数据。"/><Editor title="导出黑名单" badge="第二层" value={values.exportBlacklist} onChange={value=>setValues(current=>({...current,exportBlacklist:value}))} note="在生成最终 MissAV 导出时剔除，独立于参考库黑名单。"/></section>{notice&&<div className="notice">{notice}</div>}<div className="sticky-actions"><span>{Object.values(values).reduce((sum,value)=>sum+parseList(value).length,0).toLocaleString()} 个列表项</span><button className="primary" onClick={save} disabled={busy}>{busy?"处理中…":"保存资料库"}</button></div></div>;
}
function Editor({title,badge,value,onChange,note}:{title:string;badge:string;value:string;onChange:(value:string)=>void;note:string}){return <article className="card library-card"><div className="section-heading"><div><span className="eyebrow">{badge}</span><h3>{title}</h3></div><strong className="count-chip">{parseList(value).length.toLocaleString()}</strong></div><p>{note}</p><textarea value={value} onChange={event=>onChange(event.target.value)} spellCheck={false} placeholder="每行一个值"/></article>;}
