"use client";

import { useEffect, useMemo, useState } from "react";
import { normalizeCode, parseCsvRows, parseList } from "../../lib/rules";
import type { SanitizedImportRecord, ToolId } from "../../lib/types";

type Preview={fileName:string;checksum:string;total:number;records:SanitizedImportRecord[];rejected:number;counts:Record<string,number>};
type Batch={id:string;file_name:string;status:string;total_rows:number;valid_rows:number;rejected_rows:number;applied_rows:number;created_at:string};
const tools=new Set(["twitter","badnews","haijiao","missav"]);
async function api(url:string,options?:RequestInit){const response=await fetch(url,options);const payload=await response.json().catch(()=>({error:"请求失败"}));if(!response.ok)throw new Error(payload.error||"请求失败");return payload;}
function list(value:unknown){return Array.isArray(value)?value.map(String).map(item=>item.trim()).filter(Boolean):parseList(String(value??"").replaceAll("|","\n"));}
function record(raw:Record<string,unknown>):SanitizedImportRecord|null{const normalized=Object.fromEntries(Object.entries(raw).map(([key,value])=>[key.trim().toLowerCase().replace(/[_\s-]/g,""),value]));let tool=String(normalized.tool||normalized.type||"").toLowerCase();let primary=String(normalized.primaryvalue||normalized.primary||normalized.value||normalized.code||normalized.url||normalized.recordkey||"").trim();if(!tool){if(/^https?:\/\/(?:www\.)?bad\.news/i.test(primary))tool="badnews";else if(/haijiaolove\.xyz/i.test(primary))tool="haijiao";else if(/^@|x\.com|twitter\.com/i.test(primary))tool="twitter";else if(primary)tool="missav";}if(!tools.has(tool)||!primary)return null;if(tool==="missav")primary=normalizeCode(primary);const recordKey=String(normalized.recordkey||normalized.key||(tool==="twitter"?primary.replace(/^@/,"").toLowerCase():primary.toLowerCase())).trim();if(!recordKey)return null;return{tool:tool as ToolId,recordKey,primaryValue:primary,secondaryValue:String(normalized.secondaryvalue||normalized.secondary||normalized.note||""),status:String(normalized.status||"imported"),tags:list(normalized.tags),actressTags:list(normalized.actresstags||normalized.actress),genreTags:list(normalized.genretags||normalized.genre),sourceUrl:String(normalized.sourceurl||normalized.source||""),missavUrl:String(normalized.missavurl||""),av123Url:String(normalized.av123url||""),metadata:{migration:"sanitized-web-import"}};}
async function checksum(text:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return[...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,"0")).join("");}
function parseContent(name:string,text:string):Array<Record<string,unknown>>{if(name.toLowerCase().endsWith(".json")){const value=JSON.parse(text);if(Array.isArray(value))return value;if(value&&typeof value==="object"){const object=value as Record<string,unknown>;if(Array.isArray(object.records))return object.records as Array<Record<string,unknown>>;if(Array.isArray(object.rows))return object.rows as Array<Record<string,unknown>>;}throw new Error("JSON 必须是数组，或包含 records / rows 数组");}const rows=parseCsvRows(text);if(rows.length<2)return[];const headers=rows[0];return rows.slice(1).map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??""])));}
export default function MigrationPanel({onChanged}:{onChanged:()=>void}){const [preview,setPreview]=useState<Preview|null>(null);const [batches,setBatches]=useState<Batch[]>([]);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");
  const load=()=>api("/api/migrations").then(payload=>setBatches(payload.batches)).catch(error=>setNotice(error.message));useEffect(load,[]);
  async function selectFile(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;setNotice("");try{if(/\.(sqlite|sqlite3|db)$/i.test(file.name))throw new Error("第一版禁止直接导入正式 SQLite；请先从桌面端导出脱敏 JSON/CSV。 ");if(!/\.(json|csv)$/i.test(file.name))throw new Error("只接受脱敏 JSON 或 CSV");const text=await file.text();const raw=parseContent(file.name,text);const valid=raw.map(record).filter((item):item is SanitizedImportRecord=>Boolean(item));const unique=new Map(valid.map(item=>[`${item.tool}:${item.recordKey}`,item]));const records=[...unique.values()];const counts=records.reduce<Record<string,number>>((result,item)=>({...result,[item.tool]:(result[item.tool]||0)+1}),{});setPreview({fileName:file.name,checksum:await checksum(text),total:raw.length,records,rejected:raw.length-valid.length+(valid.length-records.length),counts});}catch(error){setPreview(null);setNotice(error instanceof Error?error.message:"无法读取文件");}}
  async function apply(){if(!preview||!preview.records.length)return;if(!window.confirm(`确认写入 ${preview.records.length.toLocaleString()} 条脱敏记录？完成后可按批次回滚。`))return;setBusy(true);try{const started=await api("/api/migrations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"start",fileName:preview.fileName,checksum:preview.checksum,totalRows:preview.total,validRows:preview.records.length,rejectedRows:preview.rejected,counts:preview.counts})});for(let offset=0;offset<preview.records.length;offset+=100){await api("/api/migrations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"append",batchId:started.batchId,records:preview.records.slice(offset,offset+100)})});setNotice(`正在写入 ${Math.min(offset+100,preview.records.length).toLocaleString()} / ${preview.records.length.toLocaleString()}`);}await api("/api/migrations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"complete",batchId:started.batchId})});setNotice("脱敏导入完成，数量已核对，可从批次列表回滚");setPreview(null);load();onChanged();}catch(error){setNotice(error instanceof Error?error.message:"导入失败");}finally{setBusy(false);}}
  async function rollback(batch:Batch){if(!window.confirm(`回滚“${batch.file_name}”批次？该批次新增记录将删除，被更新记录将恢复。`))return;setBusy(true);try{await api("/api/migrations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"rollback-start",batchId:batch.id})});let remaining=1;while(remaining>0){const step=await api("/api/migrations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"rollback-step",batchId:batch.id})});remaining=step.remaining;setNotice(`正在回滚，剩余 ${remaining.toLocaleString()} 项`);}setNotice("批次已完整回滚");load();onChanged();}catch(error){setNotice(error instanceof Error?error.message:"回滚失败");}finally{setBusy(false);}}
  const countSummary=useMemo(()=>preview?Object.entries(preview.counts).map(([key,value])=>`${key} ${value}`).join(" · "):"",[preview]);
  return <div className="stack-lg"><section className="callout warning"><strong>先脱敏，再迁移</strong><p>这里不接受 SQLite、会话文件、密钥或原始 Telegram 归档。请先从 Windows 桌面端生成脱敏 JSON/CSV；网站会先预览、统计、计算校验值，确认后才写入数据库。</p></section><section className="migration-grid"><div className="card"><span className="eyebrow">步骤 1</span><h3>选择脱敏文件</h3><label className="dropzone large"><input type="file" accept=".json,.csv" onChange={selectFile}/><strong>选择 JSON / CSV</strong><span>不会在选择后自动写入</span></label><div className="format-note"><strong>最小字段</strong><code>tool, recordKey, primaryValue</code><p>也兼容 code / url / status / tags / actressTags / genreTags 等字段。</p></div></div><div className="card"><span className="eyebrow">步骤 2</span><h3>预览与数量核对</h3>{preview?<><div className="migration-metrics"><div><strong>{preview.total.toLocaleString()}</strong><span>原始行</span></div><div><strong>{preview.records.length.toLocaleString()}</strong><span>可导入</span></div><div><strong>{preview.rejected.toLocaleString()}</strong><span>拒绝/重复</span></div></div><p className="checksum" title={preview.checksum}>SHA-256 · {preview.checksum.slice(0,18)}…</p><p className="hint">{countSummary}</p><div className="preview-rows">{preview.records.slice(0,20).map((item,index)=><div key={`${item.tool}-${item.recordKey}`}><span>{index+1}</span><span className={`tool-chip ${item.tool}`}>{item.tool}</span><strong>{item.primaryValue}</strong><small>{item.status}</small></div>)}</div><button className="primary wide" disabled={busy} onClick={apply}>{busy?"处理中…":`确认导入 ${preview.records.length.toLocaleString()} 条`}</button></>:<div className="empty compact"><strong>尚未选择文件</strong><p>文件内容会先在浏览器内解析，仅确认后分批发送到数据库。</p></div>}</div></section>{notice&&<div className="notice">{notice}</div>}<section className="card"><div className="section-heading"><div><span className="eyebrow">步骤 3</span><h3>迁移批次与回滚</h3></div><button onClick={load}>刷新</button></div><div className="batch-list">{batches.map(batch=><div key={batch.id}><div><strong>{batch.file_name}</strong><small>{new Date(batch.created_at).toLocaleString("zh-CN")} · 原始 {batch.total_rows.toLocaleString()} · 写入 {batch.applied_rows.toLocaleString()} · 拒绝 {batch.rejected_rows.toLocaleString()}</small></div><span className={`batch-status ${batch.status}`}>{batch.status}</span>{["applied","importing"].includes(batch.status)&&<button disabled={busy} onClick={()=>rollback(batch)}>回滚</button>}</div>)}{!batches.length&&<div className="empty compact"><strong>暂无迁移批次</strong><p>每次确认导入都会保存独立批次与恢复记录。</p></div>}</div></section></div>;
}
