"use client";

import { useMemo, useRef, useState } from "react";
import { processDocuments } from "../../lib/rules";
import type { InputDocument } from "../../lib/rules";
import type { ToolId, ToolResult } from "../../lib/types";

const tools:Array<{id:ToolId;mark:string;title:string;note:string}>=[
  {id:"twitter",mark:"#",title:"推特博主",note:"标签、@账号、个人页"},
  {id:"badnews",mark:"B",title:"Bad.news",note:"主题链接规范化"},
  {id:"haijiao",mark:"海",title:"海角链接",note:"限定分类与数字页"},
  {id:"missav",mark:"AV",title:"MissAV 番号",note:"降噪、去重与黑名单"},
];

function download(name:string,content:string,type="text/plain;charset=utf-8") { const url=URL.createObjectURL(new Blob([content],{type})); const a=document.createElement("a"); a.href=url;a.download=name;a.click();URL.revokeObjectURL(url); }
function csv(value:unknown){ return `"${String(value??"").replaceAll('"','""')}"`; }
async function api(url:string,options?:RequestInit){ const response=await fetch(url,options); const payload=await response.json().catch(()=>({error:"请求失败"})); if(!response.ok) throw new Error(payload.error||"请求失败"); return payload; }

export default function ToolPanel({onSaved}:{onSaved:()=>void}) {
  const [tool,setTool]=useState<ToolId>("twitter"); const [paste,setPaste]=useState(""); const [files,setFiles]=useState<InputDocument[]>([]);
  const [start,setStart]=useState(""); const [end,setEnd]=useState(""); const [results,setResults]=useState<ToolResult[]>([]); const [messageCount,setMessageCount]=useState(0);
  const [selected,setSelected]=useState<Set<number>>(new Set()); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false); const last=useRef<number|null>(null);
  const active=tools.find(item=>item.id===tool)!;
  const documents=useMemo(()=>[...(paste.trim()?[{name:"粘贴文本",text:paste}]:[]),...files],[paste,files]);
  const chosen=selected.size?results.filter((_,index)=>selected.has(index)):results;
  async function pick(event:React.ChangeEvent<HTMLInputElement>){ const picked=[...(event.target.files||[])]; const loaded=await Promise.all(picked.map(async file=>({name:file.name,text:await file.text()}))); setFiles(current=>[...current,...loaded]); event.target.value=""; }
  function run(){ try { if(!documents.length) throw new Error("请粘贴文本或添加文件"); const output=processDocuments(tool,documents,start,end); setResults(output.results);setMessageCount(output.messages.length);setSelected(new Set());setNotice(`已从 ${output.messages.length} 条消息提取 ${output.results.length} 条结果`); } catch(error){setNotice(error instanceof Error?error.message:"处理失败");} }
  function rowSelect(index:number,event:React.MouseEvent){ const next=new Set(selected); if(event.shiftKey&&last.current!==null){ const [from,to]=[last.current,index].sort((a,b)=>a-b); if(!event.ctrlKey&&!event.metaKey)next.clear(); for(let i=from;i<=to;i+=1)next.add(i); } else if(event.ctrlKey||event.metaKey){ if(next.has(index))next.delete(index);else next.add(index); } else { next.clear();next.add(index); } last.current=index;setSelected(next); }
  async function save(){ if(!results.length)return; setBusy(true);try{ await api("/api/runs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({tool,name:`${active.title} · ${new Date().toLocaleString("zh-CN")}`,inputKind:files.length?"files":"manual",startAt:start,endAt:end,sourceSummary:documents.map(item=>item.name).join(", "),results})});setNotice("结果已写入永久历史和数据中心");onSaved();}catch(error){setNotice(error instanceof Error?error.message:"保存失败");}finally{setBusy(false);} }
  function plain(){return chosen.map(item=>item.secondaryValue?`${item.primaryValue}\t${item.secondaryValue}`:item.primaryValue).join("\r\n");}
  function exportResults(format:"txt"|"csv"|"json"){ if(format==="txt")download(`${tool}-results.txt`,plain()); else if(format==="json")download(`${tool}-results.json`,JSON.stringify({tool,exportedAt:new Date().toISOString(),count:chosen.length,results:chosen},null,2),"application/json"); else download(`${tool}-results.csv`,`\uFEFF${["primary,secondary,status,source",...chosen.map(row=>[row.primaryValue,row.secondaryValue,row.status,row.source].map(csv).join(","))].join("\r\n")}`,"text/csv;charset=utf-8"); }
  function raindrop(kind:"csv"|"html") { const items=chosen.filter(item=>item.primaryValue); if(kind==="csv"){ const header=["id","title","note","excerpt","url","folder","tags","created","cover","highlights","favorite"]; const rows=items.map((item,index)=>[index+1,item.primaryValue,"","",item.secondaryValue||`https://missav.ai/cn/${item.primaryValue.toLowerCase()}`,"MissAV Manager","missav",new Date().toISOString(),"","","false"].map(csv).join(",")); download("raindrop-missav.csv",`\uFEFF${[header.map(csv).join(","),...rows].join("\r\n")}`,"text/csv;charset=utf-8"); return; } const links=items.map(item=>`<DT><A HREF="${item.secondaryValue||`https://missav.ai/cn/${item.primaryValue.toLowerCase()}`}" TAGS="missav">${item.primaryValue}</A>`).join("\n"); download("raindrop-missav.html",`<!DOCTYPE NETSCAPE-Bookmark-file-1>\n<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">\n<TITLE>MissAV Manager</TITLE>\n<H1>MissAV Manager</H1>\n<DL><p>\n${links}\n</DL><p>`,`text/html;charset=utf-8`); }
  return <div className="stack-lg">
    <section className="tool-tabs">{tools.map(item=><button key={item.id} className={tool===item.id?"active":""} onClick={()=>{setTool(item.id);setResults([]);setSelected(new Set());}}><span>{item.mark}</span><div><strong>{item.title}</strong><small>{item.note}</small></div></button>)}</section>
    <section className="workspace-grid"><div className="card input-card"><div className="section-heading"><div><span className="eyebrow">输入</span><h3>{active.title}</h3></div><span className="subtle">支持多文件</span></div><label className="field"><span>粘贴文本</span><textarea rows={12} value={paste} onChange={event=>setPaste(event.target.value)} placeholder="粘贴 Telegram 导出片段、普通文本或链接…"/></label><label className="dropzone"><input type="file" multiple accept=".txt,.html,.htm,.md,.json,.csv,.log" onChange={pick}/><strong>＋ 添加导出文件</strong><span>TXT · HTML · JSON · CSV · LOG</span></label>{files.length>0&&<div className="file-list">{files.map((file,index)=><span key={`${file.name}-${index}`}>{file.name}<button aria-label="移除" onClick={()=>setFiles(list=>list.filter((_,i)=>i!==index))}>×</button></span>)}</div>}<div className="date-grid"><label className="field"><span>开始时间</span><input type="datetime-local" value={start} onChange={event=>setStart(event.target.value)}/></label><label className="field"><span>结束时间</span><input type="datetime-local" value={end} onChange={event=>setEnd(event.target.value)}/></label></div><button className="primary wide" onClick={run}>运行 v0.5.13 规则</button><p className="hint">时间筛选只对带时间戳的 Telegram HTML/JSON 消息生效；普通粘贴文本始终参与处理。</p></div>
      <div className="card results-card"><div className="section-heading"><div><span className="eyebrow">结果预览</span><h3>{results.length.toLocaleString()} 条</h3></div><span className="subtle">{messageCount} 条输入消息</span></div>{notice&&<div className="notice">{notice}</div>}<div className="result-toolbar"><button onClick={()=>setSelected(selected.size===results.length?new Set():new Set(results.map((_,i)=>i)))}>{selected.size===results.length&&results.length?"取消全选":"全选"}</button><button onClick={()=>navigator.clipboard.writeText(plain())} disabled={!results.length}>复制</button><button onClick={save} disabled={!results.length||busy}>{busy?"保存中…":"保存永久历史"}</button></div><div className="result-list">{!results.length?<div className="empty"><span>⌁</span><strong>等待处理结果</strong><p>输入内容并运行规则后，可在这里预览、选择、复制和导出。</p></div>:results.map((item,index)=><button key={`${item.resultKey}-${index}`} className={selected.has(index)?"selected":""} onClick={event=>rowSelect(index,event)}><input type="checkbox" readOnly checked={selected.has(index)}/><span className="row-index">{index+1}</span><div><strong>{item.primaryValue}</strong><small>{item.secondaryValue||item.source||"—"}</small></div><span className="row-status">{item.status||"success"}</span></button>)}</div><div className="export-bar"><span>导出 {chosen.length.toLocaleString()} 条</span><button onClick={()=>exportResults("txt")} disabled={!results.length}>TXT</button><button onClick={()=>exportResults("csv")} disabled={!results.length}>CSV</button><button onClick={()=>exportResults("json")} disabled={!results.length}>JSON</button>{tool==="missav"&&<><button onClick={()=>raindrop("csv")} disabled={!results.length}>Raindrop CSV</button><button onClick={()=>raindrop("html")} disabled={!results.length}>书签 HTML</button></>}</div></div>
    </section>
  </div>;
}
